language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

sudo: false

script: travis_retry mvn integration-test -Pits

addons:
   apt:
      packages:
         - oracle-java8-installer # for an updated version of Java 8